version: '3'
services:
  node-poll:
    restart: "always"
    build: "./"
    ports:
      - "5000:5000"
    volumes:
      - "./../app:/usr/src/app"
    links:
        - "mongo-poll"  
  mongo-poll:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
volumes:
 mongodb:
  
#  docker-compose -f docker/docker-compose.yml up -d --build
#  docker-compose -f docker/docker-compose.yml down
#  docker-compose -f docker/docker-compose.yml logs